/**
 * BISMILLAHIR ROHMANIR ROHIYM
 *
 * PROGRAM NAME: QUR'ONI KARIM
 * AUTHOR: SAFAROV OTAMUROD YUSUFALI O'G'LI
 * FINISHED ON: 08.08.2022, at 08:00 a.m
 *
 * DESCRIPTION: Tinglovchilar Muborak Qur'oni Karim suralari qiroatlarini to'liq eshitib bahramand bo'lish, shuningdek, o'zbek tilidagi tarjimasini o'qishlari mumkin. Alloh barchamizni o'zi iymonimizni mustahkam qilsin! Ushbu ilova orqali musulmonlarga foydam tegishidan umidvorman. Barcha insonlarga Allohning roziligini qo'lga kiritish nasib qilsin!
 *
 */

package com.otamurod.quronikarim.models

class Surahs {

    private var listOfSurahs = ArrayList<String>()

    init {
        listOfSurahs.add("FOTIHA SURASI")
        listOfSurahs.add("BAQARA SURASI")
        listOfSurahs.add("OLI IMRON SURASI")
        listOfSurahs.add("NISO SURASI")
        listOfSurahs.add("MOIDA SURASI")
        listOfSurahs.add("AN'OM  SURASI")
        listOfSurahs.add("A'ROF SURASI")
        listOfSurahs.add("ANFOL SURASI")
        listOfSurahs.add("TAVBA SURASI")
        listOfSurahs.add("YUNUS SURASI")
        listOfSurahs.add("HUD SURASI")
        listOfSurahs.add("YUSUF SURASI")
        listOfSurahs.add("RA'D SURASI")
        listOfSurahs.add("IBROHIM SURASI")
        listOfSurahs.add("HIJR SURASI")
        listOfSurahs.add("NAHL SURASI")
        listOfSurahs.add("ISRO SURASI")
        listOfSurahs.add("KAHF SURASI")
        listOfSurahs.add("MARYAM SURASI")
        listOfSurahs.add("TOHA SURASI")
        listOfSurahs.add("ANBIYO SURASI")
        listOfSurahs.add("HAJ SURASI")
        listOfSurahs.add("MU'MINUN SURASI")
        listOfSurahs.add("NUR SURASI")
        listOfSurahs.add("FURQON SURASI")
        listOfSurahs.add("SHU'ARO SURASI")
        listOfSurahs.add("NAML SURASI")
        listOfSurahs.add("QASAS SURASI")
        listOfSurahs.add("ANKABUT SURASI")
        listOfSurahs.add("RUM SURASI")
        listOfSurahs.add("LUQMON SURASI")
        listOfSurahs.add("SAJDA SURASI")
        listOfSurahs.add("AHZOB SURASI")
        listOfSurahs.add("SABA' SURASI")
        listOfSurahs.add("FOTIR SURASI")
        listOfSurahs.add("YOSIN SURASI")
        listOfSurahs.add("SOFFAT SURASI")
        listOfSurahs.add("SOD SURASI")
        listOfSurahs.add("ZUMAR SURASI")
        listOfSurahs.add("G'OFIR SURASI")
        listOfSurahs.add("FUSSILAT SURASI")
        listOfSurahs.add("SHO'RO SURASI")
        listOfSurahs.add("ZUXRUF SURASI")
        listOfSurahs.add("DUXON SURASI")
        listOfSurahs.add("JOSIYA SURASI")
        listOfSurahs.add("AHQOF SURASI")
        listOfSurahs.add("MUHAMMAD SURASI")
        listOfSurahs.add("FATH SURASI")
        listOfSurahs.add("HUJUROT SURASI")
        listOfSurahs.add("QOF SURASI")
        listOfSurahs.add("ZORIYOT SURASI")
        listOfSurahs.add("TUR SURASI")
        listOfSurahs.add("NAJM SURASI")
        listOfSurahs.add("QAMAR SURASI")
        listOfSurahs.add("RAHMON SURASI")
        listOfSurahs.add("VOQEA SURASI")
        listOfSurahs.add("HADID SURASI")
        listOfSurahs.add("MUJODALA SURASI")
        listOfSurahs.add("HASHR SURASI")
        listOfSurahs.add("MUMTAHANA SURASI")
        listOfSurahs.add("SOF SURASI")
        listOfSurahs.add("JUM'A SURASI")
        listOfSurahs.add("MUNOFIQUN SURASI")
        listOfSurahs.add("TAG'OBUN SURASI")
        listOfSurahs.add("TALOQ SURASI")
        listOfSurahs.add("TAHRIM SURASI")
        listOfSurahs.add("MULK SURASI")
        listOfSurahs.add("QALAM SURASI")
        listOfSurahs.add("HAQQA SURASI")
        listOfSurahs.add("MAORIJ SURASI")
        listOfSurahs.add("NUH SURASI")
        listOfSurahs.add("JIN SURASI")
        listOfSurahs.add("MUZZAMMIL SURASI")
        listOfSurahs.add("MUDDASSIR SURASI")
        listOfSurahs.add("QIYOMAT SURASI")
        listOfSurahs.add("INSON SURASI")
        listOfSurahs.add("MURSALOT SURASI")
        listOfSurahs.add("NABA' SURASI")
        listOfSurahs.add("NAZI'AT SURASI")
        listOfSurahs.add("ABASA SURASI")
        listOfSurahs.add("TAKVIR SURASI")
        listOfSurahs.add("INFITOR SURASI")
        listOfSurahs.add("MUTOFFIFIN SURASI")
        listOfSurahs.add("INSHIQOQ SURASI")
        listOfSurahs.add("BURUJ SURASI")
        listOfSurahs.add("TORIQ SURASI")
        listOfSurahs.add("A'LO SURASI")
        listOfSurahs.add("G'OSHIYA SURASI")
        listOfSurahs.add("FAJR SURASI")
        listOfSurahs.add("BALAD SURASI")
        listOfSurahs.add("SHAMS SURASI")
        listOfSurahs.add("LAYL SURASI")
        listOfSurahs.add("ZUHO SURASI")
        listOfSurahs.add("SHARH SURASI")
        listOfSurahs.add("TIYN SURASI")
        listOfSurahs.add("ALAQ SURASI")
        listOfSurahs.add("QADR SURASI")
        listOfSurahs.add("BAYYINA SURASI")
        listOfSurahs.add("ZALZALA SURASI")
        listOfSurahs.add("ODIYAT SURASI")
        listOfSurahs.add("QORI'A SURASI")
        listOfSurahs.add("TAKOSUR SURASI")
        listOfSurahs.add("ASR SURASI")
        listOfSurahs.add("HUMAZA SURASI")
        listOfSurahs.add("FIL SURASI")
        listOfSurahs.add("QURAYSH SURASI")
        listOfSurahs.add("MO'UN SURASI")
        listOfSurahs.add("KAVSAR SURASI")
        listOfSurahs.add("KOFIRUN SURASI")
        listOfSurahs.add("NASR SURASI")
        listOfSurahs.add("MASAD SURASI")
        listOfSurahs.add("IXLOS SURASI")
        listOfSurahs.add("FALAQ SURASI")
        listOfSurahs.add("NOS SURASI")
    }

    fun getListOfSurahs(): ArrayList<String> {
        return listOfSurahs
    }
}